"""add_execution_and_project_file_tables

Revision ID: 52f849f720ff
Revises: 001
Create Date: 2026-02-09 01:08:50.250711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f849f720ff'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'STOPPED', name='executionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_id'), 'executions', ['id'], unique=False)
    op.create_index(op.f('ix_executions_project_id'), 'executions', ['project_id'], unique=False)
    op.create_table('project_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_files_id'), 'project_files', ['id'], unique=False)
    op.create_index(op.f('ix_project_files_project_id'), 'project_files', ['project_id'], unique=False)
    op.create_table('execution_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED', name='stepstatus'), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_steps_execution_id'), 'execution_steps', ['execution_id'], unique=False)
    op.create_index(op.f('ix_execution_steps_id'), 'execution_steps', ['id'], unique=False)
    op.alter_column('billing', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('billing', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('billing', 'usage_projects',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('billing', 'usage_executions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('billing', 'usage_deployments',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('billing', 'usage_api_calls',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('billing', 'limit_projects',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('billing', 'limit_executions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('billing', 'limit_deployments',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('billing', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('billing', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('deployments', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('deployments', 'project_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('deployments', 'branch',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('deployments', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('deployments', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('memories', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('memories', 'project_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('memories', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('memories', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('projects', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('projects', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('projects', 'team_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('projects', 'files_count',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('projects', 'steps_completed',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('projects', 'steps_total',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('projects', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('team_members', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('team_members', 'team_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('team_members', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('team_members', 'invited_by',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('team_members', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('teams', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('teams', 'owner_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('teams', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('teams', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('teams', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('teams', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('teams', 'owner_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('teams', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('team_members', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('team_members', 'invited_by',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('team_members', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('team_members', 'team_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('team_members', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('projects', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('projects', 'steps_total',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('projects', 'steps_completed',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('projects', 'files_count',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('projects', 'team_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('projects', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('projects', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('memories', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('memories', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('memories', 'project_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('memories', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('deployments', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('deployments', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('deployments', 'branch',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('deployments', 'project_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('deployments', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('billing', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('billing', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('billing', 'limit_deployments',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('billing', 'limit_executions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('billing', 'limit_projects',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('billing', 'usage_api_calls',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('billing', 'usage_deployments',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('billing', 'usage_executions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('billing', 'usage_projects',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('billing', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('billing', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_execution_steps_id'), table_name='execution_steps')
    op.drop_index(op.f('ix_execution_steps_execution_id'), table_name='execution_steps')
    op.drop_table('execution_steps')
    op.drop_index(op.f('ix_project_files_project_id'), table_name='project_files')
    op.drop_index(op.f('ix_project_files_id'), table_name='project_files')
    op.drop_table('project_files')
    op.drop_index(op.f('ix_executions_project_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_id'), table_name='executions')
    op.drop_table('executions')
    # ### end Alembic commands ###
